### PR TITLE
issue-#6: compiles only the importer.styl file.

### PR DESCRIPTION
**Pull request by amirmehmood**

### CODE REVIEW

**Comment by amirmehmood** [comment]
@dominiksteiner can you please review and merge?

**Comment by jodonnell-broadsoft** [comment]
Good idea

**Comment by jodonnell-broadsoft** [comment]
Sorry @dominiksteiner I did not see this was assigned to you. I hope you don't mind me merging it.

**Comment by dominiksteiner** [comment]
@jodonnell-broadsoft we were talking with Amir about a different solution so yes, please make sure to not merge tickets not assigned to you.

**Comment by jodonnell-broadsoft** [comment]
@dominiksteiner sounds good. Sorry about that

**Comment by amirmehmood** [comment]
I can't see this update in master. Not sure when it was reverted and blaming the file also didn't help. Can you please check? @dominiksteiner @jodonnell-broadsoft

**Comment by dominiksteiner** [comment]
I can see it on master

https://github.com/BroadsoftLabs/hubGruntTasks/blob/master/tasks/config/stylus.js

```
src: ['**/importer.styl'],
```

Or are you referring to something else?

**Comment by amirmehmood** [comment]
oh yes, it's there. I was looking the stylint config instead of stylus. I'm sorry about that.

**Pull request merged**
