### PR TITLE
Ja 676 unit tests webpack

### PR DESCRIPTION
**Pull request by albi34**
This is not very urgent but it will have to be merged at some point.

It was a mistake to put the webpack config files directly in the hub-grunt-tasks. In the end we'll probably need to have different webpack config depending on the integrations scripts. 

I modified the webpack grunt task to make it search for a webpack config directly in the project root directory. 

For now I didn't remove the local webpack config files as they might be helpful for copy/pasting them in the other projects.

### CODE REVIEW

**Comment by albi34** [comment]
@ahsang this will have an impact for you, feel free to check this out :)

**Comment by joncodo** [comment]
This seems fine to me to merge. Can you approve it @amirmehmood @dominiksteiner ?

**Comment by dominiksteiner** [comment]
looks good

**Comment by amirmehmood** [comment]
looks good, but is it ok to merge it before https://github.com/BroadsoftLabs/hubCore/pull/785 is tested and merged?

**Comment by dominiksteiner** [comment]
most changes should be on the backend for this PR, but yes, there would be some slight merging for the front end too

**Comment by joncodo** [comment]
This won't affect the others right now as it only affects webpack.

**Pull request merged**
